spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/crud
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
