spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: "yhm75040611?"
    driver-class-name: com.mysql.cj.jdbc.Driver
