server:
  port: 8089
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sinbla78@gmail.com
    password: 'zdhqslyfkhrsqltn'
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/crud
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  # mapper 경로 지정
  mapper-locations: query/**/*.xml
  configuration:
    map-underscore-to-camel-case: true